export type CampaignType = "crowdfund" | "startup";
export type MilestoneStatus = "completed" | "active" | "pending";

export interface Milestone {
  id: string;
  title: string;
  description: string;
  recipient: string;
  amount: number;
  status: MilestoneStatus;
  approvals: number;
}

export interface Campaign {
  id: string;
  type: CampaignType;
  category: string;
  title: string;
  description: string;
  story: string;
  cover: string;
  creator: string;
  verified: boolean;
  raised: number;
  goal: number;
  donors: number;
  daysLeft: number;
  milestones: Milestone[];
  createdAt: string;
}

const educationMilestones = (goal: number): Milestone[] => [
  {
    id: "m1",
    title: "Tuition - First Semester",
    description: "Direct payment to bursary for semester one fees.",
    recipient: "University Bursary",
    amount: Math.round(goal * 0.35),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m2",
    title: "Clinical Materials & Lab Fees",
    description: "Essential equipment and laboratory access fees.",
    recipient: "Faculty of Medicine",
    amount: Math.round(goal * 0.25),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m3",
    title: "Examination & Board Registration",
    description: "Final year board exam and licensing registration.",
    recipient: "Medical Council",
    amount: Math.round(goal * 0.2),
    status: "active",
    approvals: 1,
  },
  {
    id: "m4",
    title: "Tuition - Final Semester",
    description: "Direct payment to bursary for graduation semester.",
    recipient: "University Bursary",
    amount: Math.round(goal * 0.2),
    status: "pending",
    approvals: 0,
  },
];

const medicalMilestones = (goal: number): Milestone[] => [
  {
    id: "m1",
    title: "Pre-Operative Assessment",
    description: "Full diagnostic scans, blood work, and anesthesia prep.",
    recipient: "Lagos University Hospital",
    amount: Math.round(goal * 0.2),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m2",
    title: "Main Surgical Procedure",
    description: "Surgeon fees and operating theater costs.",
    recipient: "Surgical Team Lead",
    amount: Math.round(goal * 0.5),
    status: "active",
    approvals: 2,
  },
  {
    id: "m3",
    title: "ICU & Post-Op Recovery",
    description: "Intensive care monitoring and recovery medication.",
    recipient: "Recovery Ward Admin",
    amount: Math.round(goal * 0.2),
    status: "pending",
    approvals: 0,
  },
  {
    id: "m4",
    title: "Follow-Up & Rehabilitation",
    description: "Six-month physiotherapy and medication course.",
    recipient: "Medical Pharmacy Ltd",
    amount: Math.round(goal * 0.1),
    status: "pending",
    approvals: 0,
  },
];

const startupMilestones = (goal: number): Milestone[] => [
  {
    id: "m1",
    title: "Product Prototype & R&D",
    description: "Initial design and development of the MVP.",
    recipient: "Design & Engineering Team",
    amount: Math.round(goal * 0.3),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m2",
    title: "Marketing & Beta Launch",
    description: "User acquisition campaign and server deployment.",
    recipient: "Growth Agency",
    amount: Math.round(goal * 0.3),
    status: "active",
    approvals: 1,
  },
  {
    id: "m3",
    title: "Inventory & Fleet Expansion",
    description: "Bulk procurement of raw materials or vehicles.",
    recipient: "Verified Suppliers",
    amount: Math.round(goal * 0.3),
    status: "pending",
    approvals: 0,
  },
  {
    id: "m4",
    title: "Team Scaling & Operations",
    description: "Hiring of core staff and office infrastructure.",
    recipient: "Operations Account",
    amount: Math.round(goal * 0.1),
    status: "pending",
    approvals: 0,
  },
];

const communityMilestones = (goal: number): Milestone[] => [
  {
    id: "m1",
    title: "Survey & Resource Mobilization",
    description: "Site survey, soil testing, and equipment transport.",
    recipient: "Engineering Contractor",
    amount: Math.round(goal * 0.2),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m2",
    title: "Core Infrastructure Drilling",
    description: "Primary construction or drilling phase.",
    recipient: "Engineering Contractor",
    amount: Math.round(goal * 0.4),
    status: "active",
    approvals: 1,
  },
  {
    id: "m3",
    title: "System Fitting & Tanks",
    description: "Installation of pumps, tanks, and solar systems.",
    recipient: "Technical Sub-Contractor",
    amount: Math.round(goal * 0.3),
    status: "pending",
    approvals: 0,
  },
  {
    id: "m4",
    title: "Handover & Water Testing",
    description: "Final quality checks and community training.",
    recipient: "Water Board Authority",
    amount: Math.round(goal * 0.1),
    status: "pending",
    approvals: 0,
  },
];

const reliefMilestones = (goal: number): Milestone[] => [
  {
    id: "m1",
    title: "Beneficiary Verification",
    description: "Identifying and vetting affected recipients.",
    recipient: "Community Board",
    amount: Math.round(goal * 0.1),
    status: "completed",
    approvals: 4,
  },
  {
    id: "m2",
    title: "Bulk Inventory Procurement",
    description: "Purchasing materials from verified wholesalers.",
    recipient: "Verified Wholesalers",
    amount: Math.round(goal * 0.5),
    status: "active",
    approvals: 2,
  },
  {
    id: "m3",
    title: "Distribution & Delivery",
    description: "Direct handover of resources to beneficiaries.",
    recipient: "Logistics Partner",
    amount: Math.round(goal * 0.3),
    status: "pending",
    approvals: 0,
  },
  {
    id: "m4",
    title: "Impact Monitoring",
    description: "Post-distribution audit and feedback.",
    recipient: "Auditing Firm",
    amount: Math.round(goal * 0.1),
    status: "pending",
    approvals: 0,
  },
];

// Crowdfund: exactly 1 milestone = full goal amount
const crowdfundMilestone = (goal: number, title: string, description: string, recipient: string): Milestone[] => [
  {
    id: "m1",
    title,
    description,
    recipient,
    amount: goal,
    status: "active",
    approvals: 0,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "amaka-medical-school",
    type: "crowdfund",
    category: "Education",
    title: "Help Amaka Finish Medical School",
    description:
      "Final year medical student in Uyo needs tuition, hostel, and exam fees paid directly to her university.",
    story:
      "Amaka is a final-year medical student at the University of Uyo who has consistently ranked in the top 5% of her class. Throughout her journey, she has demonstrated an unwavering commitment to healthcare, balancing a demanding curriculum with community service. However, the recent economic downturn has severely impacted her family's small business, leaving them unable to cover the final stretch of her education.\n\nHer academic record is exemplary:\n• Maintained a 4.2 CGPA over five years of study.\n• Volunteered over 200 hours at the Uyo Teaching Hospital.\n• Co-authored a research paper on pediatric nutrition in rural Akwa Ibom.\n\nThe funds requested here are critical for her to complete her final clinical rotations and sit for the medical board exams. Without this support, she faces the risk of being withdrawn from the program just months before graduation. We have structured this campaign to ensure every cUSD is spent directly on academic requirements:\n1. Direct payment of tuition to the University Bursary.\n2. Clinical rotation fees paid to the hospital administration.\n3. Medical Board examination registration fees.\n\nUpon graduation, Amaka plans to remain in Uyo to serve the very community that helped her finish her degree. Her goal is to specialize in Maternal and Child Health, addressing the high mortality rates in the region. By supporting this campaign, you aren't just funding a student; you are investing in the health of an entire community.",
    cover:
      "linear-gradient(135deg, oklch(0.4 0.1 110), oklch(0.18 0 0))",
    creator: "0x9aF3...c2D1",
    verified: true,
    raised: 4200,
    goal: 6300,
    donors: 184,
    daysLeft: 12,
    milestones: crowdfundMilestone(6300, "Full Academic Fees Payment", "Direct payment of all tuition, clinical, and board exam fees to the university bursary.", "University Bursary"),
    createdAt: "2025-03-14",
  },
  {
    id: "kemi-threads",
    type: "startup",
    category: "Fashion Tech",
    title: "Kemi Threads - African Streetwear DTC",
    description:
      "Lagos-based fashion brand raising tranche-1 funding to launch flagship collection. Milestone-gated investor protection.",
    story:
      "Kemi Threads is building Africa's first vertically integrated streetwear brand, focusing on high-quality materials and authentic local designs. We believe that African fashion is the next global frontier, yet many local brands lack the capital and supply chain infrastructure to scale effectively. Our mission is to bridge this gap while ensuring absolute transparency for our investors.\n\nThe opportunity is massive:\n• African fashion market is projected to reach $15.5B by 2027.\n• 70% increase in local demand for high-quality, 'Made in Nigeria' streetwear.\n• Established supply chain partnerships with 12 local textile artisans.\n\nWe are raising this seed round using TruSTFUnd's milestone-gated model to ensure that capital is deployed efficiently and responsibly. Investors have full visibility into our operations and can pull out unspent tranches if we fail to meet our growth targets. Our roadmap is divided into three clear phases:\n1. Finalizing the prototype collection and securing bulk raw materials.\n2. Launching our e-commerce platform and initial marketing campaign.\n3. Expanding our Lagos warehouse to support regional distribution.\n\nOur team brings over 15 years of combined experience in fashion design and logistics. We aren't just selling clothes; we are building a brand that represents the spirit of modern Africa. Join us in taking Kemi Threads from a Lagos studio to a global stage.",
    cover: "linear-gradient(135deg, oklch(0.45 0.18 295), oklch(0.18 0 0))",
    creator: "0x12cA...88eF",
    verified: true,
    raised: 38000,
    goal: 80000,
    donors: 27,
    daysLeft: 22,
    milestones: startupMilestones(80000),
    createdAt: "2025-02-28",
  },
  {
    id: "tunde-surgery",
    type: "crowdfund",
    category: "Medical",
    title: "Tunde's Heart Surgery Fund",
    description:
      "Emergency cardiac surgery - funds released directly to hospital and surgeon.",
    cover: "linear-gradient(135deg, oklch(0.5 0.2 25), oklch(0.18 0 0))",
    story:
      "Tunde is a 34-year-old father of two who has recently been diagnosed with a critical heart condition that requires immediate surgical intervention. As the sole provider for his young family, this diagnosis has brought not only health concerns but an immense financial burden that they cannot carry alone.\n\nMedical Status & Requirements:\n• Diagnosed with severe valvular heart disease requiring replacement.\n• Recommended for surgery by top specialists at Lagos University Teaching Hospital.\n• Post-operative care requires 6 months of specialized monitoring and medication.\n\nDue to the high cost of specialized cardiac surgery in Nigeria, we are raising funds in stages to ensure the hospital and surgical teams are paid directly. This milestone-gated approach ensures that every donor's contribution is used exactly for its intended clinical purpose. The funding is structured as follows:\n1. Pre-operative testing and surgical preparation fees.\n2. The main cardiac surgery and intensive care unit costs.\n3. Post-operative recovery, rehabilitation, and long-term medication.\n\nTunde has a bright future ahead of him and dreams of watching his children grow up. By contributing to this fund, you are giving a young father a second chance at life. All funds are held in escrow and released only upon verification of hospital invoices by our medical validators.",
    creator: "0x55Bc...01aA",
    verified: true,
    raised: 9100,
    goal: 12000,
    donors: 312,
    daysLeft: 5,
    milestones: crowdfundMilestone(12000, "Full Cardiac Surgery & Recovery", "Direct payment of all surgical, ICU, and post-operative recovery costs to the hospital.", "Lagos University Hospital"),
    createdAt: "2025-04-01",
  },
  {
    id: "farmlink-saas",
    type: "startup",
    category: "AgriTech",
    title: "FarmLink - SaaS for Smallholder Farmers",
    description:
      "Pre-seed angel round. Milestone-protected. Smallholder logistics platform across West Africa.",
    cover: "linear-gradient(135deg, oklch(0.5 0.16 150), oklch(0.18 0 0))",
    story:
      "FarmLink is a logistics and data platform designed specifically for the 12,000+ smallholder farmers across West Africa who currently lose up to 40% of their harvest due to poor supply chain access. We provide a seamless link between rural producers and urban buyers through a simple SMS and USSD-based marketplace.\n\nOur Market Impact:\n• Reduction of post-harvest waste by an estimated 25% for active users.\n• Average increase in farmer income of $450 per season.\n• Real-time pricing transparency for over 15 essential crop varieties.\n\nWe are utilizing TruSTFUnd's milestone-gated investment model to scale our operations into three new regions this year. This ensures that our angel investors' capital is protected and tied directly to our growth and infrastructure milestones. Our primary scaling objectives include:\n1. Deployment of cold-storage collection centers in 5 key rural hubs.\n2. Expansion of our USSD marketplace to support 5 additional local languages.\n3. Integration with local fintech partners for instant payment settlements.\n\nOur team is composed of former logistics experts and agricultural scientists with deep roots in the communities we serve. We believe that by digitizing the agricultural supply chain, we can ensure food security and prosperity for millions of smallholder farmers.",
    creator: "0x77Ae...44bD",
    verified: false,
    raised: 14500,
    goal: 50000,
    donors: 9,
    daysLeft: 30,
    milestones: startupMilestones(50000),
    createdAt: "2025-03-22",
  },
  {
    id: "school-borehole",
    type: "crowdfund",
    category: "Community",
    title: "Clean Water Borehole - Ekiti Primary",
    description:
      "Drill a borehole for a 600-pupil primary school. Vendor-direct disbursement.",
    cover: "linear-gradient(135deg, oklch(0.5 0.14 200), oklch(0.18 0 0))",
    story:
      "The Ekiti Primary School serves over 600 pupils from the surrounding villages, yet for the last five years, it has functioned without a reliable source of clean water. Currently, students and staff are forced to walk over 2 kilometers to a local stream, which often dries up during the harmattan season and is prone to waterborne contaminants.\n\nProjected Impact of Clean Water:\n• 90% expected reduction in waterborne illnesses among the student population.\n• Reclaiming over 500 hours of monthly instructional time lost to water collection.\n• Improved sanitation and hygiene facilities for 300+ female students.\n\nThis project will fund the drilling of a deep-well borehole equipped with a solar-powered pump and storage tanks. To ensure total transparency, funds are released directly to our vetted engineering contractor only after each stage of the project is verified by the community board. The project phases are:\n1. Geological survey and initial drilling to the water table.\n2. Installation of the solar pumping system and 5,000L storage tanks.\n3. Construction of the distribution taps and final water quality testing.\n\nClean water is a fundamental right that every child deserves. Your contribution will directly transform the educational environment at Ekiti Primary, ensuring that these students can focus on their studies instead of their survival.",
    creator: "0x33De...77cC",
    verified: true,
    raised: 2800,
    goal: 4500,
    donors: 96,
    daysLeft: 18,
    milestones: crowdfundMilestone(4500, "Borehole Drilling & Installation", "Full procurement and installation of the borehole, solar pump, and storage tanks.", "Engineering Contractor"),
    createdAt: "2025-04-10",
  },
  {
    id: "skola-app",
    type: "startup",
    category: "EdTech",
    title: "Skola - Offline-First Learning App",
    description:
      "Series-Pre-A. Mobile learning for low-bandwidth regions. Tranche-protected.",
    cover: "linear-gradient(135deg, oklch(0.45 0.2 265), oklch(0.18 0 0))",
    story:
      "Skola is an offline-first educational platform designed to provide high-quality learning materials to students in regions with low-bandwidth or expensive data costs. Having already served over 80,000 students across Kenya and Nigeria, we are now seeking to expand our content library and technical infrastructure to reach the next million learners.\n\nWhy Skola is Different:\n• Proprietary compression tech that allows video lessons to load on 2G connections.\n• Gamified curriculum aligned with national education standards.\n• Teacher dashboard for tracking student progress without constant internet.\n\nThis Pre-A round is structured to protect our investors by tying capital release to clear user growth and product development milestones. We believe in building a sustainable business that also delivers massive social impact. Our immediate growth roadmap includes:\n1. Production of 500+ new STEM video lessons in local dialects.\n2. Infrastructure upgrades to support up to 500,000 concurrent users.\n3. Launch of our 'Skola for Schools' B2B pilot program with 50 rural institutions.\n\nEducation is the most powerful tool for changing the world, and at Skola, we are making sure that data costs aren't a barrier to that tool. Join us in democratizing access to world-class education for every African child.",
    creator: "0x88Cd...22ff",
    verified: true,
    raised: 62000,
    goal: 100000,
    donors: 41,
    daysLeft: 9,
    milestones: startupMilestones(100000),
    createdAt: "2025-03-05",
  },
  // New Crowdfunds
  {
    id: "solargrid-africa",
    type: "crowdfund",
    category: "Infrastructure",
    title: "SolarGrid Africa",
    description: "Equipping a community maternity ward with solar panels for 24/7 lighting and vaccine storage.",
    cover: "linear-gradient(135deg, oklch(0.6 0.15 80), oklch(0.18 0 0))",
    story:
      "SolarGrid Africa is a mission-driven project dedicated to bringing reliable power to rural clinics. The Gboko Rural Clinic is a lifeline for over 15,000 residents in the surrounding area, yet it currently lacks reliable electricity. The maternity ward often has to deliver babies by candlelight or kerosene lamps, and the clinic frequently loses expensive vaccines due to refrigeration failures during power outages.\n\nSolar Solution Benefits:\n• 24/7 lighting for the emergency and maternity wards.\n• Reliable cold-chain storage for life-saving vaccines and medications.\n• Reduced operational costs by eliminating expensive petrol generators.\n\nBy funding this campaign, you are paying directly for the procurement and installation of a professional-grade solar power system. Funds are released in tranches to the solar installation company only after our community validators confirm each stage of the setup. The installation plan is:\n1. Procurement of high-efficiency solar panels and deep-cycle batteries.\n2. Professional installation of the rooftop array and inverter system.\n3. Wiring of the maternity ward and installation of the medical refrigerator.\n\nNo woman should have to give birth in the dark, and no child should miss a vaccine because of a power cut. Help us bring reliable, clean energy to the Gboko Clinic and save lives in the process.",
    creator: "0x11Aa...99Bb",
    verified: true,
    raised: 1200,
    goal: 3500,
    donors: 45,
    daysLeft: 14,
    milestones: crowdfundMilestone(3500, "Solar System Procurement & Installation", "Full procurement and installation of solar panels, batteries, and clinic wiring.", "Solar Installation Co."),
    createdAt: "2025-04-12",
  },
  {
    id: "market-fire",
    type: "crowdfund",
    category: "Relief",
    title: "Aba Market Fire - Merchant Recovery",
    description: "Restocking kits for 10 small stall owners who lost everything in the Aba central market fire.",
    cover: "linear-gradient(135deg, oklch(0.4 0.25 30), oklch(0.18 0 0))",
    story:
      "The recent central market fire in Aba was a devastating blow to the local economy, particularly for the small-scale merchants who lost their entire inventory in a single night. For many of these stall owners, their business was their only source of livelihood, and without insurance, they have no way to restock and restart.\n\nRecovery Strategy:\n• Direct provision of inventory credit to 10 most-affected small merchants.\n• Negotiated bulk pricing with verified wholesalers to maximize fund impact.\n• Business mentorship to help merchants improve their fire safety and bookkeeping.\n\nInstead of providing cash, this campaign funds 'Restocking Kits' paid directly to verified wholesalers. This ensures that the capital is used exclusively to rebuild the merchants' businesses and stimulate the local market economy. The recovery milestones are:\n1. Verification and selection of the 10 most-affected small merchants.\n2. First batch of inventory procurement and delivery to temporary stalls.\n3. Second batch of inventory and completion of the merchant business training.\n\nThe spirit of Aba is resilient, but our neighbors need a helping hand to get back on their feet. Your support will directly help 10 families regain their financial independence and restore the heart of our community's commerce.",
    creator: "0x22Bb...88Cc",
    verified: true,
    raised: 5600,
    goal: 15000,
    donors: 230,
    daysLeft: 7,
    milestones: crowdfundMilestone(15000, "Merchant Restocking — All 10 Stalls", "Bulk inventory procurement paid directly to verified wholesalers for all affected merchants.", "Verified Wholesalers"),
    createdAt: "2025-04-18",
  },
  {
    id: "student-bus",
    type: "crowdfund",
    category: "Inclusion",
    title: "Accessible Van for Inclusive School",
    description: "Customized transport for students with physical disabilities at the Hope Academy.",
    cover: "linear-gradient(135deg, oklch(0.5 0.18 220), oklch(0.18 0 0))",
    story:
      "Hope Academy is a pioneer in inclusive education, providing specialized support for students with physical disabilities alongside their able-bodied peers. However, the lack of accessible transportation is a massive barrier, as many students struggle to reach the school safely using standard commercial buses or motorcycles.\n\nTransportation Goals:\n• Safe, daily transport for 40 students with mobility challenges.\n• Customized vehicle equipped with an automated hydraulic lift and safety restraints.\n• Reduction in school absenteeism by an estimated 35%.\n\nThis campaign will fund the purchase and professional conversion of a specialized accessible van. To maintain transparency, funds will be released directly to the vehicle dealership and the specialized conversion workshop. Our procurement steps are:\n1. Initial deposit and purchase of a high-roof transit van.\n2. Installation of the hydraulic lift, interior floor leveling, and safety locks.\n3. Final inspection, licensing, and branding of the Hope Academy Inclusive Bus.\n\nEducation is only powerful if you can actually get to the classroom. By supporting this van, you are quite literally opening the door to education for children who have been left behind for far too long.",
    creator: "0x33Cc...77Dd",
    verified: true,
    raised: 8900,
    goal: 25000,
    donors: 112,
    daysLeft: 25,
    milestones: crowdfundMilestone(25000, "Accessible Van Purchase & Conversion", "Full purchase and wheelchair conversion of the Hope Academy inclusive transport van.", "Vehicle Dealership & Conversion Workshop"),
    createdAt: "2025-04-05",
  },
  {
    id: "community-library",
    type: "crowdfund",
    category: "Education",
    title: "Books for Ikot Ekpene Library",
    description: "Restocking the youth wing with STEM textbooks and modern literature.",
    cover: "linear-gradient(135deg, oklch(0.4 0.1 180), oklch(0.18 0 0))",
    story:
      "The Ikot Ekpene Library was once a vibrant hub of learning, but today its shelves are filled with outdated materials that don't reflect the needs of modern students. In an era of rapid technological change, our youth deserve access to the same STEM and contemporary literature that students in major cities enjoy.\n\nLibrary Revitalization Plan:\n• Acquisition of 1,000+ new titles focusing on Science, Tech, and Modern Fiction.\n• Establishment of a dedicated 'Innovation Corner' with digital learning resources.\n• Hosting monthly reading clubs and science workshops for local youth.\n\nWe are raising funds to restock the library's youth wing. To ensure every dollar is accounted for, we pay the publishers and authorized book distributors directly. We will never handle the cash ourselves. The restocking milestones are:\n1. Procurement of the primary STEM and curriculum-aligned textbook list.\n2. Purchase of the contemporary literature and vocational training guides.\n3. Installation of the new shelving units and digital reading tablets.\n\nA library is the heart of a thinking community. By helping us restock Ikot Ekpene, you are giving thousands of young minds the fuel they need to dream, learn, and build a better future.",
    creator: "0x44Dd...66Ee",
    verified: true,
    raised: 1500,
    goal: 3000,
    donors: 67,
    daysLeft: 10,
    milestones: crowdfundMilestone(3000, "Full Book Procurement & Shelving", "Purchase of all STEM, modern literature, and vocational titles paid directly to publishers.", "Authorised Book Distributors"),
    createdAt: "2025-04-15",
  },
  {
    id: "elderly-home",
    type: "crowdfund",
    category: "Social Care",
    title: "Owerri Elderly Home Repairs",
    description: "Fixing leaking roofs and installing safety railings for the Saint Jude's care home.",
    cover: "linear-gradient(135deg, oklch(0.45 0.1 50), oklch(0.18 0 0))",
    story:
      "Saint Jude's Care Home has been a sanctuary for the elderly in Owerri for over three decades, but the facility is currently in a state of disrepair. Multiple sections of the roof leak during the rainy season, and several common areas lack the basic safety railings and anti-slip flooring necessary to prevent dangerous falls among our residents.\n\nPriority Repair Areas:\n• Replacement of 400sqm of roofing across the main residential wing.\n• Installation of industrial-grade safety railings in all bathrooms and corridors.\n• Upgrading of the emergency lighting system for night-time safety.\n\nWe are seeking funds to complete these critical repairs and ensure that our residents can live in the dignity and safety they deserve. Every cUSD raised will be paid directly to the construction and safety contractors. Our repair schedule is:\n1. Complete roof replacement and waterproofing of the west wing.\n2. Installation of all safety railings and anti-slip flooring in common areas.\n3. Final inspection and certification of the home's safety standards.\n\nOur elders are the keepers of our history and wisdom. By supporting Saint Jude's, you are showing them that they haven't been forgotten. Help us provide a safe, dry, and comfortable home for those who have spent their lives caring for us.",
    creator: "0x55Ee...55Ff",
    verified: true,
    raised: 4200,
    goal: 8000,
    donors: 89,
    daysLeft: 20,
    milestones: crowdfundMilestone(8000, "Roof Repairs & Safety Upgrades", "Full roof replacement, safety railings, and emergency lighting for Saint Jude's Care Home.", "Construction & Safety Contractor"),
    createdAt: "2025-04-02",
  },
  {
    id: "football-academy",
    type: "crowdfund",
    category: "Sports",
    title: "Kano Stars Youth Kit Fund",
    description: "Boots, balls, and jerseys for an under-17 community team in Kano.",
    cover: "linear-gradient(135deg, oklch(0.5 0.2 120), oklch(0.18 0 0))",
    story:
      "The Kano Stars Academy was founded on the belief that sports can be a powerful vehicle for social change and youth empowerment. In a region where opportunities for young people can be limited, our academy provides a structured environment where boys under the age of 17 can develop their athletic talents while receiving mentorship and academic support.\n\nAcademy Resource Needs:\n• 40 pairs of professional-grade football boots and 20 match-quality balls.\n• Full home and away kits for two complete youth squads.\n• Basic first-aid and sports rehabilitation equipment.\n\nWe are raising funds to provide our young athletes with the equipment they need to compete at a higher level. To ensure transparency, we have partnered with local sports vendors who will be paid directly from the TruSTFUnd escrow. The equipment rollout is:\n1. Procurement of the primary training kits and match balls.\n2. Purchase of professional football boots for all registered academy players.\n3. Setup of the academy's first-aid station and training equipment lockers.\n\nInvesting in grassroots sports is an investment in the discipline, health, and future of our youth. Your contribution will help the Kano Stars shine on and off the pitch, giving these young men a chance to pursue their dreams with confidence.",
    creator: "0x66Ff...44Gg",
    verified: false,
    raised: 800,
    goal: 2000,
    donors: 34,
    daysLeft: 15,
    milestones: crowdfundMilestone(2000, "Full Kit — Boots, Balls & Jerseys", "Procurement of all football boots, match balls, and home/away kits from vetted sports vendors.", "Local Sports Vendors"),
    createdAt: "2025-04-20",
  },
  {
    id: "apprentice-tools",
    type: "crowdfund",
    category: "Livelihood",
    title: "Carpentry Tools for Ibrahim",
    description: "A complete set of professional power tools for a graduating apprentice in Kaduna.",
    cover: "linear-gradient(135deg, oklch(0.4 0.12 40), oklch(0.18 0 0))",
    story:
      "Ibrahim is a dedicated young man who has recently completed a rigorous 4-year apprenticeship under a master carpenter in Kaduna. He has mastered the skills of furniture making and structural carpentry, but like many talented graduates from vocational programs, he lacks the initial capital to purchase the tools required to open his own independent workshop.\n\nEssential Tool Kit:\n• Professional-grade table saw and cordless drill set.\n• Heavy-duty router and finishing sanders for high-quality furniture production.\n• A complete set of precision hand tools and safety gear.\n\nThis campaign is designed to provide Ibrahim with a 'Business Starter Kit' that will allow him to immediately begin taking on contracts and hiring his own junior apprentices. We pay the tool depot directly for a pre-approved list of professional equipment. The tool distribution plan is:\n1. Purchase of the core power tool set and precision measurement guides.\n2. Procurement of the heavy-duty workbench and structural assembly tools.\n3. Final setup of the workshop and initial stock of seasoned hardwood.\n\nEmpowering a skilled artisan is one of the most effective ways to create sustainable economic growth. By helping Ibrahim start his shop, you are supporting a new business that will eventually provide employment for others in the Kaduna community.",
    creator: "0x77Gg...33Hh",
    verified: true,
    raised: 600,
    goal: 1200,
    donors: 28,
    daysLeft: 3,
    milestones: crowdfundMilestone(1200, "Professional Tool Kit Purchase", "Full purchase of power tools, hand tools, and safety gear from the verified tool depot.", "Tool Depot"),
    createdAt: "2025-04-22",
  },
  // New Startups
  {
    id: "agro-p2p",
    type: "startup",
    category: "Fintech",
    title: "Seeds - P2P Lending for Farmers",
    description: "Micro-credit platform for input financing. Raising for regional pilot expansion.",
    cover: "linear-gradient(135deg, oklch(0.5 0.15 140), oklch(0.18 0 0))",
    story:
      "Seeds is a peer-to-peer lending platform designed to unlock the productive potential of rural Africa by connecting urban capital directly to smallholder farmers. Traditional banks often view rural agriculture as too risky, leaving farmers with no choice but to use high-interest informal lenders. Seeds provides a transparent, tech-driven alternative.\n\nOur Platform Goals:\n• Facilitate micro-loans for seeds, fertilizer, and basic equipment.\n• Implement a proprietary 'Yield-Based' credit scoring model.\n• Achieve a 95%+ repayment rate through community-based accountability.\n\nWe are raising this expansion round to take our successful pilot program to three additional agricultural regions. TruSTFUnd's milestone-gated model ensures that our investors' capital is used to build the necessary regulatory and technical infrastructure. Our expansion milestones are:\n1. Securing the necessary regional micro-lending licenses and legal compliance.\n2. Onboarding 1,000 new farmers onto the platform through rural field agents.\n3. Launching our automated 'Crop-Insurance' integration for loan protection.\n\nBy digitizing trust and credit in rural communities, we are turning small farms into viable businesses. Join us in building the financial infrastructure that will power the next green revolution in Africa.",
    creator: "0x88Hh...22Ii",
    verified: true,
    raised: 25000,
    goal: 60000,
    donors: 15,
    daysLeft: 40,
    milestones: startupMilestones(60000),
    createdAt: "2025-03-25",
  },
  {
    id: "health-mobile",
    type: "startup",
    category: "HealthTech",
    title: "SonoScan - Mobile Ultrasound",
    description: "Portable diagnostics for maternal health in hard-to-reach regions.",
    cover: "linear-gradient(135deg, oklch(0.45 0.18 250), oklch(0.18 0 0))",
    story:
      "SonoScan is tackling the critical issue of maternal mortality in hard-to-reach rural regions through the deployment of portable, AI-enhanced ultrasound technology. In many remote communities, expectant mothers have to travel for days to access basic prenatal diagnostics, leading to high rates of undetected complications.\n\nOur Health Impact:\n• Deployment of 10 ultra-portable 'ScanStick' devices to rural midwives.\n• Real-time cloud-based review of scans by certified radiologists.\n• 40% expected reduction in undetected high-risk pregnancy complications.\n\nWe are seeking investment to scale our fleet of devices and train a new cohort of community health workers. TruSTFUnd's milestone model ensures that funds are released only as we achieve our clinical and operational goals. Our roadmap is:\n1. Procurement of 10 'ScanStick' units and localized AI diagnostic software.\n2. Training and certification of 20 community midwives in basic ultrasound use.\n3. Establishment of our regional 'Tele-Radiology' hub for remote scan reviews.\n\nEarly detection saves lives. At SonoScan, we are making sure that a mother's location doesn't determine her survival. Join us in bringing life-saving technology to the world's most vulnerable communities.",
    creator: "0x99Ii...11Jj",
    verified: true,
    raised: 45000,
    goal: 120000,
    donors: 52,
    daysLeft: 28,
    milestones: medicalMilestones(120000),
    createdAt: "2025-03-10",
  },
  {
    id: "clean-nairobi",
    type: "startup",
    category: "CleanTech",
    title: "EcoPlastic - Nairobi Circularity",
    description: "End-to-end plastic collection and upcycling into construction bricks.",
    cover: "linear-gradient(135deg, oklch(0.55 0.2 160), oklch(0.18 0 0))",
    story:
      "EcoPlastic is a circular economy startup in Nairobi that is transforming the city's plastic waste crisis into a sustainable construction solution. We collect low-value plastic waste—which would otherwise clog our waterways or be burned—and upcycle it into high-durability, eco-friendly construction bricks for affordable housing.\n\nSustainability & Scaling:\n• Diverting 50 tons of plastic waste from Nairobi landfills every month.\n• Creating 100+ dignified jobs for local waste collectors and factory workers.\n• Producing bricks that are 20% cheaper and 5x more durable than traditional clay.\n\nWe are raising capital to build our first full-scale industrial upcycling facility. Using TruSTFUnd's milestone-gated model, we provide our investors with absolute certainty that their capital is being used for tangible industrial assets. Our facility milestones are:\n1. Leasing the industrial site and securing all environmental permits.\n2. Procurement and installation of our proprietary 'EcoPress' brick machinery.\n3. Acquisition of a fleet of 5 solar-powered collection tricycles.\n\nWaste is only waste if we don't know how to use it. At EcoPlastic, we are building the homes of tomorrow using the problems of today. Join us in making Nairobi a cleaner, greener, and more prosperous city.",
    creator: "0xAAJj...00Kk",
    verified: true,
    raised: 78000,
    goal: 200000,
    donors: 84,
    daysLeft: 45,
    milestones: startupMilestones(200000),
    createdAt: "2025-02-15",
  },
  {
    id: "logi-e-bike",
    type: "startup",
    category: "Logistics",
    title: "VoltDelivery - E-Bike Fleet",
    description: "Last-mile green delivery across Accra. Subscription model for local vendors.",
    cover: "linear-gradient(135deg, oklch(0.4 0.2 100), oklch(0.18 0 0))",
    story:
      "VoltDelivery is Ghana's first zero-emission last-mile logistics provider, serving the bustling streets of Accra with a fleet of high-efficiency electric bikes. By eliminating fuel costs and reducing maintenance requirements, we provide local vendors with a delivery service that is both cheaper and more reliable than traditional petrol-powered alternatives.\n\nLogistics Excellence:\n• 100% emission-free deliveries using solar-charged battery swaps.\n• 30% reduction in delivery costs for our partner micro-merchants.\n• Proprietary AI routing that optimizes for e-bike battery life and traffic.\n\nWe are seeking funding to acquire our next 50 electric bikes and set up our primary solar-powered charging and battery-swap hub. TruSTFUnd's gated tranches allow us to grow our fleet in lock-step with our merchant demand. Our growth phases are:\n1. Procurement and assembly of 25 'Volt-1' heavy-duty electric delivery bikes.\n2. Setup of the central Accra 'VoltHub' solar charging and maintenance center.\n3. Launch of our integrated 'Vendor-App' for seamless order management.\n\nAccra is moving faster than ever, and VoltDelivery is making sure that growth doesn't come at the cost of our environment. Join us in powering the future of African urban logistics.",
    creator: "0xBBKk...99Ll",
    verified: false,
    raised: 12000,
    goal: 45000,
    donors: 11,
    daysLeft: 35,
    milestones: startupMilestones(45000),
    createdAt: "2025-04-05",
  },
  {
    id: "coding-bootcamp",
    type: "startup",
    category: "EdTech",
    title: "CodeHaus - Youth Bootcamp",
    description: "Intensive 6-month software engineering school for high-potential youth.",
    cover: "linear-gradient(135deg, oklch(0.4 0.22 320), oklch(0.18 0 0))",
    story:
      "CodeHaus is an intensive, 6-month software engineering school designed to turn high-potential African youth into world-class developers. We focus on project-based learning and direct industry placements, bridging the massive gap between traditional academic theory and the practical needs of the global tech economy.\n\nOur Educational Model:\n• Curriculum focused on React, Node.js, and Blockchain development.\n• Income Share Agreement (ISA) model to ensure accessibility for all.\n• 85% placement rate within 3 months of graduation for our pilot cohort.\n\nWe are raising funds to lease a dedicated campus and procure the hardware necessary for our next cohort of 100 students. Our milestone-gated model ensures that capital is deployed only as we hit our educational and placement targets. Our roadmap is:\n1. Securing a long-term lease for the CodeHaus Lagos Innovation Campus.\n2. Procurement of 100 high-performance laptops and high-speed satellite internet.\n3. Onboarding our faculty of industry-expert mentors and guest lecturers.\n\nThe talent in Africa is evenly distributed, but the opportunity is not. CodeHaus is here to fix that balance. Join us in training the engineers who will build the digital future of the continent.",
    creator: "0xCCLl...88Mm",
    verified: true,
    raised: 30000,
    goal: 75000,
    donors: 24,
    daysLeft: 19,
    milestones: educationMilestones(75000),
    createdAt: "2025-03-20",
  },
  {
    id: "urban-agri",
    type: "startup",
    category: "AgriTech",
    title: "Lagos Greens - Container Farming",
    description: "Hydroponic vertical farms in reused shipping containers across Lagos.",
    cover: "linear-gradient(135deg, oklch(0.5 0.15 130), oklch(0.18 0 0))",
    story:
      "Lagos Greens is pioneering the future of urban agriculture through the deployment of high-tech, hydroponic vertical farms inside repurposed shipping containers. By growing produce directly in the heart of Lagos, we eliminate the need for long-distance transportation, which currently accounts for significant food waste and carbon emissions in the city.\n\nOur Urban Farming Advantages:\n• 90% less water usage compared to traditional soil-based farming.\n• Zero pesticides or herbicides used in our controlled environment systems.\n• Harvest-to-table delivery within 2 hours, ensuring peak nutritional value.\n\nWe are seeking investment to build and deploy our next ten 'GreenContainers' in strategic urban locations. Our milestone-gated model provides investors with clear evidence of our hardware fabrication and crop production success. Our expansion plan includes:\n1. Fabrication of 5 vertical farming containers with climate control and LED arrays.\n2. Establishing our primary hydroponic nutrient production facility in Ikeja.\n3. Launching our 'FreshBox' subscription service for local Lagos restaurants.\n\nThe future of food is local, sustainable, and tech-driven. At Lagos Greens, we are proving that you don't need a field to grow a forest of fresh produce. Join us in building a more resilient and healthy food system for Lagos.",
    creator: "0xDDMm...77Nn",
    verified: true,
    raised: 15000,
    goal: 55000,
    donors: 33,
    daysLeft: 24,
    milestones: startupMilestones(55000),
    createdAt: "2025-03-28",
  },
  {
    id: "msme-saas",
    type: "startup",
    category: "SaaS",
    title: "KwikStock - MSME Inventory",
    description: "Inventory and sales tracking for small retail shops. USSD enabled.",
    cover: "linear-gradient(135deg, oklch(0.45 0.12 280), oklch(0.18 0 0))",
    story:
      "KwikStock is an intuitive, USSD-enabled inventory management and sales tracking platform designed specifically for the millions of micro-merchants and retail shop owners across Africa. Most of these businesses currently rely on paper notebooks, which are prone to loss and make it impossible to track business health or access credit.\n\nMerchant Empowerment Features:\n• Offline-first inventory logging via simple USSD codes and SMS.\n• Real-time sales analytics and automated low-stock alerts.\n• Integrated 'Credit-Score' generation based on verified sales history.\n\nWe are raising capital to launch our beta program and recruit a dedicated merchant acquisition team in three major commercial hubs. Our milestone-gated investment structure ensures that we are meeting our merchant adoption and retention goals. Our immediate objectives are:\n1. Completion of the USSD gateway integration and backend analytics dashboard.\n2. Hiring and training of 15 'Market-Ambassadors' for on-ground merchant onboarding.\n3. Achieving our first 5,000 active daily merchants across the beta regions.\n\nData is the key to unlocking the true potential of Africa's retail economy. With KwikStock, we are giving small merchants the tools they need to professionalize, scale, and eventually access the formal financial system.",
    creator: "0xEENn...66Oo",
    verified: true,
    raised: 8000,
    goal: 30000,
    donors: 14,
    daysLeft: 31,
    milestones: startupMilestones(30000),
    createdAt: "2025-04-02",
  },
  {
    id: "remote-hr",
    type: "startup",
    category: "HRTech",
    title: "AfriWork - Global Talent Bridge",
    description: "Vetting and placement platform for African remote software engineers.",
    cover: "linear-gradient(135deg, oklch(0.5 0.15 210), oklch(0.18 0 0))",
    story:
      "AfriWork is a specialized talent bridge that connects world-class software engineers from across the African continent to high-growth global technology companies. While the talent in Africa is abundant, many developers struggle with the legal, financial, and logistical complexities of international remote work. We handle the friction so they can focus on the code.\n\nTalent & Trust Infrastructure:\n• Rigorous multi-stage vetting process including technical and soft-skill audits.\n• Integrated payroll and compliance systems for seamless cross-border payments.\n• Ongoing mentorship and career development for all placed engineers.\n\nWe are seeking funding to build out our automated testing platform and expand our legal compliance infrastructure into five new international markets. TruSTFUnd's gated model ensures that our investors are supporting a business that scales with verified placements. Our roadmap is:\n1. Launch of our automated 'Code-Audit' vetting platform for 10+ languages.\n2. Securing legal and tax compliance partnerships in the US, UK, and EU.\n3. Reaching our milestone of 250 successful long-term engineer placements.\n\nThe global remote work revolution is here, and Africa's engineers are ready to lead. Join us in building the infrastructure that will make the continent the primary talent hub for the 21st-century digital economy.",
    creator: "0xFFOo...55Pp",
    verified: true,
    raised: 21000,
    goal: 50000,
    donors: 19,
    daysLeft: 12,
    milestones: startupMilestones(50000),
    createdAt: "2025-04-10",
  },
  {
    id: "paygo-solar",
    type: "startup",
    category: "Energy",
    title: "SunLink - PAYGO Microgrids",
    description: "Pay-as-you-go solar energy for off-grid residential communities.",
    cover: "linear-gradient(135deg, oklch(0.55 0.18 70), oklch(0.18 0 0))",
    story:
      "SunLink is a clean energy startup focused on providing reliable, pay-as-you-go (PAYGO) solar microgrids to off-grid residential communities. In many regions, the cost of traditional solar systems is a barrier to adoption. Our model allows families to access clean energy for a small daily fee, making power affordable for everyone.\n\nClean Energy Accessibility:\n• 100% renewable energy sourced from high-efficiency local solar arrays.\n• Smart IoT meters that allow for easy mobile-money payments (M-Pesa, cUSD).\n• 50% lower average cost compared to traditional kerosene or petrol power.\n\nWe are raising capital to procure our next generation of microgrid hardware and set up our primary IoT monitoring and maintenance center. Using TruSTFUnd's milestone tranches, we ensure that every cUSD is tied to the physical deployment of power. Our scaling milestones are:\n1. Procurement of 500 'SunLink-Gen2' smart meters and solar controller units.\n2. Construction of our first community 'PowerHub' in a rural pilot village.\n3. Launch of our mobile app for real-time energy usage and payment tracking.\n\nAccess to energy is access to opportunity. At SunLink, we are lighting up the dark and powering the dreams of thousands of families. Join us in building a cleaner, brighter, and more equitable future for all.",
    creator: "0xGGPp...44Qq",
    verified: true,
    raised: 85000,
    goal: 250000,
    donors: 67,
    daysLeft: 50,
    milestones: communityMilestones(250000),
    createdAt: "2025-02-20",
  },
  {
    id: "bus-ticket",
    type: "startup",
    category: "Mobility",
    title: "RideTick - Digital Bus Booking",
    description: "Unified digital ticketing for inter-city bus travel across West Africa.",
    cover: "linear-gradient(135deg, oklch(0.4 0.1 0), oklch(0.18 0 0))",
    story:
      "RideTick is a unified digital ticketing and booking platform designed to modernize the fragmented inter-city bus travel industry across West Africa. Currently, travelers face long queues, unpredictable pricing, and a lack of reliable scheduling. We are bringing the convenience of digital booking to the millions of people who rely on road travel every day.\n\nModernizing Mobility:\n• Centralized booking app with real-time seat availability and transparent pricing.\n• Integrated QR-code validation for seamless, paperless boarding.\n• 20% expected reduction in bus operator 'Dead-Head' mileage through better data.\n\nWe are seeking investment to integrate our first ten major bus operators and launch a targeted marketing campaign in major transit hubs. TruSTFUnd's milestone model ensures that our growth is backed by real operator adoption. Our immediate goals are:\n1. Finalizing the technical integration with 5 major regional bus operators.\n2. Launching the RideTick mobile app on iOS and Android with cUSD support.\n3. Achieving 10,000 successful ticket bookings within the first three months.\n\nTraveling across Africa should be as easy as tapping a screen. At RideTick, we are removing the friction from the journey and building the digital backbone of continental mobility. Join us in making travel safer, faster, and more reliable for everyone.",
    creator: "0xHHQq...33Rr",
    verified: false,
    raised: 5000,
    goal: 20000,
    donors: 8,
    daysLeft: 38,
    milestones: startupMilestones(20000),
    createdAt: "2025-04-15",
  },
];

export const getCampaign = (id: string) =>
  campaigns.find((c) => c.id === id) ?? campaigns[0];